# Generated by Django 3.1.5 on 2021-01-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='base_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='base_number',
        ),
        migrations.AddField(
            model_name='document',
            name='base',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.basedocument'),
        ),
    ]
