# Generated by Django 3.1.5 on 2021-01-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20210109_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedocument',
            name='date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
        migrations.AlterModelTable(
            name='basedocument',
            table='base_document',
        ),
    ]
